// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: user.proto

package userpb

import (
	pb "example/proto/common/pb"
	fmt "fmt"
	_ "github.com/xieweiyu/protoc-gen-rpc-dispatcher/gendispatcher"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for User service

func NewUserEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for User service

type UserService interface {
	// 统一入口，标记为 dispatcher，protoc-gen-rpc-dispatcher 会跳过它
	CallAPI(ctx context.Context, in *pb.APIRequest, opts ...client.CallOption) (*pb.APIResponse, error)
	// 获取用户信息 — 会被自动生成 wrapper handler
	GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...client.CallOption) (*GetUserInfoResponse, error)
	// 用户登录 — 会被自动生成 wrapper handler
	Login(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*LoginResponse, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) CallAPI(ctx context.Context, in *pb.APIRequest, opts ...client.CallOption) (*pb.APIResponse, error) {
	req := c.c.NewRequest(c.name, "User.CallAPI", in)
	out := new(pb.APIResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...client.CallOption) (*GetUserInfoResponse, error) {
	req := c.c.NewRequest(c.name, "User.GetUserInfo", in)
	out := new(GetUserInfoResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Login(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*LoginResponse, error) {
	req := c.c.NewRequest(c.name, "User.Login", in)
	out := new(LoginResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for User service

type UserHandler interface {
	// 统一入口，标记为 dispatcher，protoc-gen-rpc-dispatcher 会跳过它
	CallAPI(context.Context, *pb.APIRequest, *pb.APIResponse) error
	// 获取用户信息 — 会被自动生成 wrapper handler
	GetUserInfo(context.Context, *GetUserInfoRequest, *GetUserInfoResponse) error
	// 用户登录 — 会被自动生成 wrapper handler
	Login(context.Context, *LoginRequest, *LoginResponse) error
}

func RegisterUserHandler(s server.Server, hdlr UserHandler, opts ...server.HandlerOption) error {
	type user interface {
		CallAPI(ctx context.Context, in *pb.APIRequest, out *pb.APIResponse) error
		GetUserInfo(ctx context.Context, in *GetUserInfoRequest, out *GetUserInfoResponse) error
		Login(ctx context.Context, in *LoginRequest, out *LoginResponse) error
	}
	type User struct {
		user
	}
	h := &userHandler{hdlr}
	return s.Handle(s.NewHandler(&User{h}, opts...))
}

type userHandler struct {
	UserHandler
}

func (h *userHandler) CallAPI(ctx context.Context, in *pb.APIRequest, out *pb.APIResponse) error {
	return h.UserHandler.CallAPI(ctx, in, out)
}

func (h *userHandler) GetUserInfo(ctx context.Context, in *GetUserInfoRequest, out *GetUserInfoResponse) error {
	return h.UserHandler.GetUserInfo(ctx, in, out)
}

func (h *userHandler) Login(ctx context.Context, in *LoginRequest, out *LoginResponse) error {
	return h.UserHandler.Login(ctx, in, out)
}
