// protoc-gen-rpc-dispatcher — protoc 插件，从 proto 生成 API 调度器
//
// 安装:
//
//	go install github.com/loomy/protoc-gen-rpc-dispatcher@latest
//
// 用法:
//
//	protoc --rpc-dispatcher_out=OUT_DIR --rpc-dispatcher_opt=module=xxx \
//	       --proto_path=proto --proto_path=path/to/protoc-gen-rpc-dispatcher/proto \
//	       your_service.proto
//
// 在每个 proto 子目录的 pb/ 目录下生成 xxx_dispatcher_gen.go，
// 包含自动 JSON 序列化/反序列化的 RPC 调度器

package main

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"

	"google.golang.org/genproto/googleapis/api/annotations"

	"github.com/loomy/protoc-gen-rpc-dispatcher/genrouter"
)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			if err := generateFile(gen, f); err != nil {
				gen.Error(err)
			}
		}
		return nil
	})
}

// generateFile 为单个 proto 文件生成 dispatcher 代码
func generateFile(gen *protogen.Plugin, f *protogen.File) error {
	for _, svc := range f.Services {
		if err := genServiceDispatcher(gen, f, svc); err != nil {
			return fmt.Errorf("service %s: %w", svc.Desc.Name(), err)
		}
	}
	return nil
}

// genServiceDispatcher 为一个 service 生成 dispatcher 文件
func genServiceDispatcher(gen *protogen.Plugin, f *protogen.File, svc *protogen.Service) error {
	// 收集非 CallAPI 的 RPC
	type rpcEntry struct {
		Name         string
		RequestType  string
		ResponseType string
		HTTPMethod   string
		HTTPPath     string
		ActionName   string
		IsCallAPI    bool
	}

	var rpcs []rpcEntry
	for _, method := range svc.Methods {
		methodName := string(method.Desc.Name())

		// 跳过标记为 is_dispatcher 的 RPC（用户定义的 dispatcher 入口）
		methodOpts := method.Desc.Options().(*descriptorpb.MethodOptions)
		if genrouter.IsDispatcherRPC(methodOpts) {
			continue
		}

		// 提取 HTTP 注解
		httpMethod, httpPath := extractHTTPAnnotation(method)

		// 推导 action 名
		actionName := deriveActionName(methodName, httpPath)

		// 取请求/响应类型名（去掉包名前缀）
		reqType := string(method.Input.Desc.Name())
		respType := string(method.Output.Desc.Name())

		rpcs = append(rpcs, rpcEntry{
			Name:         methodName,
			RequestType:  reqType,
			ResponseType: respType,
			HTTPMethod:   httpMethod,
			HTTPPath:     httpPath,
			ActionName:   actionName,
			IsCallAPI:    false,
		})
	}

	if len(rpcs) == 0 {
		return nil
	}

	// 确定输出路径
	// 输入 proto 路径: user_service/user.proto
	// pb 导入路径:     micro-test/pkg/proto/user_service/pb
	// dispatcher 路径: micro-test/pkg/proto/user_service/dispatcher
	// 输出文件名:      pkg/proto/user_service/dispatcher/user_dispatcher_gen.go
	protoDir := f.Desc.Path()
	dirIdx := strings.LastIndex(protoDir, "/")
	baseName := strings.TrimSuffix(protoDir[dirIdx+1:], ".proto")

	// 构建 dispatcher 的 Go import path
	// 将 pb 导入路径的最后一段 "pb" 替换为 "dispatcher"
	pbImportPath := string(f.GoImportPath)
	dispatcherImportPath := replaceLastSegment(pbImportPath, "dispatcher")

	// 构建文件名：使用完整的 import path 作为相对路径（protogen 会自动处理 module 前缀）
	filename := dispatcherImportPath + "/" + baseName + "_dispatcher_gen.go"

	// 包名
	svcLower := strings.ToLower(string(svc.Desc.Name()))
	pkgName := svcLower + "dispatcher"

	// pb 包别名
	pbAlias := string(f.GoPackageName)

	// 生成文件 — 使用正确的 dispatcher 导入路径和文件名
	g := gen.NewGeneratedFile(filename, protogen.GoImportPath(dispatcherImportPath))
	g.P("// Code generated by protoc-gen-router. DO NOT EDIT.")

	// 生成代码
	g.P("// 源文件: ", protoDir)
	g.P("// 服务: ", svc.Desc.Name())
	g.P("//")
	g.P("// 使用方式:")
	g.P("//")
	g.P("//   type ", svc.Desc.Name(), "Impl struct {")
	g.P("//       // 你的业务依赖")
	g.P("//   }")
	for _, rpc := range rpcs {
		g.P("//   func (s *", svc.Desc.Name(), "Impl) ", rpc.Name, "(ctx context.Context, req *", pbAlias, ".", rpc.RequestType, ") (*", pbAlias, ".", rpc.ResponseType, ", error) {")
		g.P("//       // 业务逻辑")
		g.P("//   }")
	}
	g.P("//")
	g.P("//   // 在 main 中:")
	g.P("//   dispatcher := ", pkgName, ".New", svc.Desc.Name(), "Dispatcher(&", svc.Desc.Name(), "Impl{...})")
	g.P("//   // 在 CallAPI 中:")
	g.P("//   data, err := dispatcher.Dispatch(ctx, req.Action, []byte(req.Params))")
	g.P()

	g.P("package ", pkgName)
	g.P()
	g.P("import (")
	g.P("    \"context\"")
	g.P("    \"encoding/json\"")
	g.P("    \"fmt\"")
	g.P()
	g.P("    ", pbAlias, " \"", pbImportPath, "\"")
	g.P(")")
	g.P()

	// 生成接口
	g.P("// ", svc.Desc.Name(), "Server 是 ", svc.Desc.Name(), " 服务需要实现的业务接口")
	g.P("type ", svc.Desc.Name(), "Server interface {")
	for _, rpc := range rpcs {
		g.P("    ", rpc.Name, "(ctx context.Context, req *", pbAlias, ".", rpc.RequestType, ") (*", pbAlias, ".", rpc.ResponseType, ", error)")
	}
	g.P("}")
	g.P()

	// 生成 Dispatcher 结构体
	g.P("// ", svc.Desc.Name(), "Dispatcher 包装 ", svc.Desc.Name(), "Server，提供统一调度")
	g.P("type ", svc.Desc.Name(), "Dispatcher struct {")
	g.P("    srv      ", svc.Desc.Name(), "Server")
	g.P("    handlers map[string]func(ctx context.Context, data []byte) ([]byte, error)")
	g.P("}")
	g.P()

	// 构造函数
	g.P("// New", svc.Desc.Name(), "Dispatcher 创建调度器")
	g.P("func New", svc.Desc.Name(), "Dispatcher(srv ", svc.Desc.Name(), "Server) *", svc.Desc.Name(), "Dispatcher {")
	g.P("    d := &", svc.Desc.Name(), "Dispatcher{")
	g.P("        srv:      srv,")
	g.P("        handlers: make(map[string]func(ctx context.Context, data []byte) ([]byte, error)),")
	g.P("    }")
	for _, rpc := range rpcs {
		g.P("    d.handlers[\"", rpc.ActionName, "\"] = d.handle", rpc.Name)
	}
	g.P("    return d")
	g.P("}")
	g.P()

	// Dispatch 方法
	g.P("// Dispatch 根据 action 名称分发请求，完成 JSON 自动序列化/反序列化")
	g.P("func (d *", svc.Desc.Name(), "Dispatcher) Dispatch(ctx context.Context, action string, data []byte) ([]byte, error) {")
	g.P("    handler, ok := d.handlers[action]")
	g.P("    if !ok {")
	g.P("        return nil, fmt.Errorf(\"action not found: %s\", action)")
	g.P("    }")
	g.P("    return handler(ctx, data)")
	g.P("}")
	g.P()

	// 每个 RPC 的 wrapper handler
	for _, rpc := range rpcs {
		g.P("func (d *", svc.Desc.Name(), "Dispatcher) handle", rpc.Name, "(ctx context.Context, data []byte) ([]byte, error) {")
		g.P("    req := &", pbAlias, ".", rpc.RequestType, "{}")
		g.P("    if err := json.Unmarshal(data, req); err != nil {")
		g.P("        return nil, fmt.Errorf(\"json unmarshal error: %w\", err)")
		g.P("    }")
		g.P("    res, err := d.srv.", rpc.Name, "(ctx, req)")
		g.P("    if err != nil {")
		g.P("        return nil, err")
		g.P("    }")
		g.P("    return json.Marshal(res)")
		g.P("}")
		g.P()
	}

	return nil
}

// extractHTTPAnnotation 从 method 的 options 中提取 google.api.http 注解
func extractHTTPAnnotation(method *protogen.Method) (methodName, path string) {
	opts := method.Desc.Options().(*descriptorpb.MethodOptions)
	if opts == nil {
		return "", ""
	}

	if !proto.HasExtension(opts, annotations.E_Http) {
		return "", ""
	}

	httpRule, ok := proto.GetExtension(opts, annotations.E_Http).(*annotations.HttpRule)
	if !ok || httpRule == nil {
		return "", ""
	}

	switch rule := httpRule.Pattern.(type) {
	case *annotations.HttpRule_Get:
		return "GET", rule.Get
	case *annotations.HttpRule_Post:
		return "POST", rule.Post
	case *annotations.HttpRule_Put:
		return "PUT", rule.Put
	case *annotations.HttpRule_Delete:
		return "DELETE", rule.Delete
	case *annotations.HttpRule_Patch:
		return "PATCH", rule.Patch
	}
	return "", ""
}

// deriveActionName 推导 action 名
// 有 HTTP 路径时取最后一段，否则转 RPC 名为 lowerCamelCase
func deriveActionName(rpcName, httpPath string) string {
	if httpPath != "" {
		parts := strings.Split(strings.TrimRight(httpPath, "/"), "/")
		return parts[len(parts)-1]
	}
	return toLowerCamelCase(rpcName)
}

func toLowerCamelCase(s string) string {
	if len(s) == 0 {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

// replaceLastSegment 替换路径的最后一段
// micro-test/pkg/proto/gateway_service/pb → micro-test/pkg/proto/gateway_service/dispatcher
func replaceLastSegment(path, newSegment string) string {
	parts := strings.Split(path, "/")
	if len(parts) > 0 {
		parts[len(parts)-1] = newSegment
	}
	return strings.Join(parts, "/")
}