// Code generated by protoc-gen-rpc-dispatcher. DO NOT EDIT.
// 源文件: user.proto
// 服务: User
//
// 使用方式:
//
//   type UserImpl struct {
//       // 你的业务依赖
//   }
//   func (s *UserImpl) GetUserInfo(ctx context.Context, req *GetUserInfoRequest) (*GetUserInfoResponse, error) {
//       // 业务逻辑
//   }
//   func (s *UserImpl) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
//       // 业务逻辑
//   }
//
//   // 启动时注册业务实现:
//   func init() {
//       userpb.Register(&UserImpl{...})
//   }
//
//   // CallAPI 中直接调用:
//   func (s *UserImpl) CallAPI(ctx context.Context, req *pb.APIRequest) (*pb.APIResponse, error) {
//       return userpb.CallAPI(ctx, req)
//   }

package userpb

import (
	"context"
	"encoding/json"
	"fmt"

	pb "example/proto/common/pb"
)

// UserServer 是 User 服务需要实现的业务接口
type UserServer interface {
	GetUserInfo(ctx context.Context, req *GetUserInfoRequest) (*GetUserInfoResponse, error)
	Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error)
}

type handlerWrap func(ctx context.Context, data []byte) (*pb.APIResponse, error)

// userServiceHandler 实现了 go-micro 生成的 UserHandler 接口
// 同时提供 CallAPI 的 action 分发能力
type userServiceHandler struct {
	srv      UserServer
	handlers map[string]handlerWrap
}

var defaultHandler *userServiceHandler

// Register 注册业务实现，必须在服务启动时调用
func Register(s UserServer) {
	defaultHandler = &userServiceHandler{
		srv:      s,
		handlers: make(map[string]handlerWrap),
	}
	defaultHandler.register()
}

// NewUserHandler 返回 go-micro 的 Handler 实现，供 RegisterUserHandler 使用
func NewUserHandler() UserHandler {
	if defaultHandler == nil {
		panic("userpb.Register() must be called before NewUserHandler()")
	}
	return defaultHandler
}

func (u *userServiceHandler) register() {
	u.handlers["getUserInfo"] = u.handleGetUserInfo
	u.handlers["login"] = u.handleLogin
}

func (u *userServiceHandler) handleGetUserInfo(ctx context.Context, data []byte) (*pb.APIResponse, error) {
	req := &GetUserInfoRequest{}
	if err := json.Unmarshal(data, req); err != nil {
		return &pb.APIResponse{Code: 400, Message: fmt.Sprintf("json unmarshal error: %v", err)}, nil
	}
	res, err := u.srv.GetUserInfo(ctx, req)
	if err != nil {
		return &pb.APIResponse{Code: 500, Message: err.Error()}, nil
	}
	d, _ := json.Marshal(res)
	return &pb.APIResponse{Code: 0, Data: d}, nil
}

func (u *userServiceHandler) handleLogin(ctx context.Context, data []byte) (*pb.APIResponse, error) {
	req := &LoginRequest{}
	if err := json.Unmarshal(data, req); err != nil {
		return &pb.APIResponse{Code: 400, Message: fmt.Sprintf("json unmarshal error: %v", err)}, nil
	}
	res, err := u.srv.Login(ctx, req)
	if err != nil {
		return &pb.APIResponse{Code: 500, Message: err.Error()}, nil
	}
	d, _ := json.Marshal(res)
	return &pb.APIResponse{Code: 0, Data: d}, nil
}

// CallAPI 实现 go-micro 的 Handler 接口，根据 action 分发请求
func (u *userServiceHandler) CallAPI(ctx context.Context, req *pb.APIRequest, out *pb.APIResponse) error {
	handler, ok := u.handlers[req.Action]
	if !ok {
		out.Code = 404
		out.Message = "action not found: " + req.Action
		return nil
	}
	resp, err := handler(ctx, []byte(req.Params))
	if err != nil {
		return err
	}
	*out = *resp
	return nil
}

func (u *userServiceHandler) GetUserInfo(ctx context.Context, req *GetUserInfoRequest, out *GetUserInfoResponse) error {
	res, err := u.srv.GetUserInfo(ctx, req)
	if err != nil {
		return err
	}
	*out = *res
	return nil
}

func (u *userServiceHandler) Login(ctx context.Context, req *LoginRequest, out *LoginResponse) error {
	res, err := u.srv.Login(ctx, req)
	if err != nil {
		return err
	}
	*out = *res
	return nil
}
