// Code generated by protoc-gen-rpc-dispatcher. DO NOT EDIT.
// 源文件: user.proto
// 服务: User
//
// 使用方式:
//
//   type UserImpl struct {
//       // 你的业务依赖
//   }
//   func (s *UserImpl) GetUserInfo(ctx context.Context, req *GetUserInfoRequest) (*GetUserInfoResponse, error) {
//       // 业务逻辑
//   }
//   func (s *UserImpl) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
//       // 业务逻辑
//   }
//
//   // 在 CallAPI 中直接使用（CallAPI 与业务代码同包，无需额外 import）:
//   func (s *UserImpl) CallAPI(ctx context.Context, req *pb.APIRequest) (*pb.APIResponse, error) {
//       return CallAPI(s)(ctx, req)
//   }

package userpb

import (
	"context"
	"encoding/json"
	"fmt"

	pb "example/proto/common/pb"
)

// UserServer 是 User 服务需要实现的业务接口
type UserServer interface {
	GetUserInfo(ctx context.Context, req *GetUserInfoRequest) (*GetUserInfoResponse, error)
	Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error)
}

// CallAPI 返回一个完整的 CallAPI 处理函数
// 传入业务接口实现，返回可直接作为 CallAPI 使用的 handler
func CallAPI(srv UserServer) func(ctx context.Context, req *pb.APIRequest) (*pb.APIResponse, error) {
	handlers := map[string]func(ctx context.Context, data []byte) *pb.APIResponse{
		"getUserInfo": func(ctx context.Context, data []byte) *pb.APIResponse {
			req := &GetUserInfoRequest{}
			if err := json.Unmarshal(data, req); err != nil {
				return &pb.APIResponse{Code: 400, Message: fmt.Sprintf("json unmarshal error: %v", err)}
			}
			res, err := srv.GetUserInfo(ctx, req)
			if err != nil {
				return &pb.APIResponse{Code: 500, Message: err.Error()}
			}
			d, _ := json.Marshal(res)
			return &pb.APIResponse{Code: 0, Data: d}
		},
		"login": func(ctx context.Context, data []byte) *pb.APIResponse {
			req := &LoginRequest{}
			if err := json.Unmarshal(data, req); err != nil {
				return &pb.APIResponse{Code: 400, Message: fmt.Sprintf("json unmarshal error: %v", err)}
			}
			res, err := srv.Login(ctx, req)
			if err != nil {
				return &pb.APIResponse{Code: 500, Message: err.Error()}
			}
			d, _ := json.Marshal(res)
			return &pb.APIResponse{Code: 0, Data: d}
		},
	}

	return func(ctx context.Context, req *pb.APIRequest) (*pb.APIResponse, error) {
		handler, ok := handlers[req.Action]
		if !ok {
			return &pb.APIResponse{Code: 404, Message: "action not found: " + req.Action}, nil
		}
		return handler(ctx, []byte(req.Params)), nil
	}
}
