// Code generated by protoc-gen-rpc-dispatcher. DO NOT EDIT.
// 源文件: user.proto
// 服务: User
//
// 使用方式:
//
//   type UserImpl struct {
//       // 你的业务依赖
//   }
//   func (s *UserImpl) GetUserInfo(ctx context.Context, req *GetUserInfoRequest) (*GetUserInfoResponse, error) {
//       // 业务逻辑
//   }
//   func (s *UserImpl) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
//       // 业务逻辑
//   }
//
//   // 启动时注册业务实现:
//   func init() {
//       userpb.Register(&UserImpl{...})
//   }
//
//   // CallAPI 中直接调用:
//   func (s *UserImpl) CallAPI(ctx context.Context, req *pb.APIRequest) (*pb.APIResponse, error) {
//       return userpb.CallAPI(ctx, req)
//   }

package userpb

import (
	"context"
	"encoding/json"
	"fmt"

	pb "example/proto/common/pb"
)

// UserServer 是 User 服务需要实现的业务接口
type UserServer interface {
	GetUserInfo(ctx context.Context, req *GetUserInfoRequest) (*GetUserInfoResponse, error)
	Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error)
}

// HandlerWrap 是一个 action 处理函数
type HandlerWrap func(ctx context.Context, data []byte) (*pb.APIResponse, error)

var (
	srv      UserServer
	handlers = make(map[string]HandlerWrap)
)

// Register 注册业务实现，必须在服务启动时调用
func Register(s UserServer) {
	srv = s
}

func init() {
	handlers["getUserInfo"] = handleGetUserInfo
	handlers["login"] = handleLogin
}

func handleGetUserInfo(ctx context.Context, data []byte) (*pb.APIResponse, error) {
	req := &GetUserInfoRequest{}
	if err := json.Unmarshal(data, req); err != nil {
		return &pb.APIResponse{Code: 400, Message: fmt.Sprintf("json unmarshal error: %v", err)}, nil
	}
	res, err := srv.GetUserInfo(ctx, req)
	if err != nil {
		return &pb.APIResponse{Code: 500, Message: err.Error()}, nil
	}
	d, _ := json.Marshal(res)
	return &pb.APIResponse{Code: 0, Data: d}, nil
}

func handleLogin(ctx context.Context, data []byte) (*pb.APIResponse, error) {
	req := &LoginRequest{}
	if err := json.Unmarshal(data, req); err != nil {
		return &pb.APIResponse{Code: 400, Message: fmt.Sprintf("json unmarshal error: %v", err)}, nil
	}
	res, err := srv.Login(ctx, req)
	if err != nil {
		return &pb.APIResponse{Code: 500, Message: err.Error()}, nil
	}
	d, _ := json.Marshal(res)
	return &pb.APIResponse{Code: 0, Data: d}, nil
}

// CallAPI 根据 action 分发请求，是统一的调度入口
func CallAPI(ctx context.Context, req *pb.APIRequest) (*pb.APIResponse, error) {
	handler, ok := handlers[req.Action]
	if !ok {
		return &pb.APIResponse{Code: 404, Message: "action not found: " + req.Action}, nil
	}
	return handler(ctx, []byte(req.Params))
}
